# ---------------------------------------------------------------------------
# Example deployment descriptor for the RYVN platform (https://ryvn.app)
# ---------------------------------------------------------------------------
# This file is OPTIONAL.
# It demonstrates how you might package and deploy the Slack-bot services
# on the RYVN deployment platform.  If you use a different CI/CD solution
# or infrastructure provider, feel free to delete or ignore this file and
# provide your own deployment configuration instead.
# ---------------------------------------------------------------------------
name: your_company-slack-bot
registry:
  type: ecr
  region: us-west-2
  account: "<AWS_ACCOUNT_ID>"
components:
  - name: web-server
    type: service
    dockerfile: Dockerfile
    port: 8000
    image: your_company-slack-bot-web
    registry:
      region: us-west-2
  - name: ai-service
    type: service
    dockerfile: ai-microservice/Dockerfile
    port: 8001
    image: your_company-slack-bot-ai
    registry:
      region: us-west-2
environments:
  - name: staging
    channel: stable
    namespace: your_company-staging
    registry:
      region: us-west-2
channels:
  - name: stable
    branch: main
  - name: pr
    pull_request: true